name: No PRs
on:
  pull_request:
    types: [opened, reopened]
jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr close "$PR" -c 'https://github.com/jcbhmr/.github'
        env:
          PR: ${{ github.event.pull_request.number }}
